[package]
name = "sequila-core"
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
datafusion = "35.0.0"
log = "0.4.20"
env_logger = "0.11.1"