name: Criterion.rs Example
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run SeQuiLa-native benchmark
    runs-on: [self-hosted, Linux, openstack-ii]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run benchmark
        run: RUSTFLAGS="-Ctarget-cpu=native" cargo bench --bench databio_benchmark -- --quick --output-format bencher | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Criterion.rs Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          alert-comment-cc-users: '@mwiewior'